kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: memcacheds.cache.example.com
spec:
  group: cache.example.com
  names:
    plural: memcacheds
    singular: memcached
    shortNames:
      - mc
    kind: Memcached
    listKind: MemcachedList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Memcached is the Schema for MyCustomResource API
          type: object
          properties:
            apiVersion:
              description: >-
                APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values. More
                info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: >-
                Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the
                client submits requests to. Cannot be updated. In CamelCase.
                More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: Memcached.spec describes the desired state of my resource
              type: object
              required:
                - size
              properties:
                size:
                  description: >-
                    The size of our Memcached cluster.
                  type: number
            status:
              description: The status of this Memcached resource, set by the operator.
              type: object
              properties:
                pods:
                  description: The list of pods created by the operator.
                  type: array
                  items:
                    description: The name of a pod created by the operator.
                    type: string
      subresources:
        status: {}
      additionalPrinterColumns:
  conversion:
    strategy: None
