apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"ts-operator:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ts-operator\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: ts-operator
    app.kubernetes.io/component: ts-operator
    app.kubernetes.io/instance: ts-operator
  name: ts-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: ts-operator
  template:
    metadata:
      labels:
        deployment: ts-operator
    spec:
      containers:
        - env:
            - name: DEV_MODE
              value: 'false'
          image: quay.io/gradde/ts-operator:latest
          imagePullPolicy: IfNotPresent
          name: ts-operator
          ports:
            - containerPort: 8080
              protocol: TCP
      serviceAccount: ts-operator
