apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: ts-operator
    app.kubernetes.io/component: ts-operator
    app.kubernetes.io/instance: ts-operator
  name: ts-operator
spec:
  lookupPolicy:
    local: false